### ISSUE TITLE
LHARK archive support?

### ISSUE THREAD

**Issue by roytam1** [fragglet/lhasa#20]
I wonder if LHARK-generated archive be supported by lhasa?
ftp://ftp.sac.sk/pub/sac/pack/lhark04d.zip

**Comment by fragglet** [comment]
Yes, I would very much like this. Unfortunately there is no publicly available source code to this tool. I have made efforts in the past to find and contact Kerwin Medina, the author, but have not had any success. Otherwise it's a matter of reverse engineering the tool to discover the encoding - either by disassembly of the code or through some black box method. Based on some investigations I believe it's a variant on -lh5-.

**Comment by polluks** [comment]
Indeed, http://www.compression.ru/arctest/self/lhark.htm.

**Comment by roytam1** [comment]
LHARK 0.4d unpacked with CUP386 v3.4
[LHARK_.zip](https://github.com/fragglet/lhasa/files/1016270/LHARK_.zip)

**Comment by roytam1** [comment]
just found this: https://entropymine.wordpress.com/2020/12/24/notes-on-lhark-compression-format/

**Comment by fragglet** [comment]
Nice!

**Comment by fragglet** [comment]
Now fixed - thanks!

**Comment by fragglet** [comment]
@jsummers - and thank you for your writeup!
